In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from sklearn.model_selection import GridSearchCV, RandomizedSearchCV
from sklearn.metrics import classification_report
import joblib

In [ ]:
df = pd.read_csv("data_clustering.csv")

In [ ]:
# Tampilkan 5 baris pertama dengan function head
df.head()

,TransactionAmount,TransactionType,Location,Channel,CustomerAge,CustomerOccupation,TransactionDuration,LoginAttempts,AccountBalance,New_Column,Target
0,14.09,1,36,0,70.0,0,81.0,1.0,5112.21,0,labels
1,376.24,1,15,0,68.0,0,141.0,1.0,13758.91,0,labels
2,126.29,1,23,2,19.0,3,56.0,1.0,1122.35,1,labels
3,184.50,1,33,2,26.0,3,25.0,1.0,8569.06,1,labels
4,92.15,1,28,0,18.0,3,172.0,1.0,781.68,1,labels

In [ ]:
categorical_cols = list(df.select_dtypes(include=['object']).columns.drop('Target'))

df_encoded = pd.get_dummies(
    df,
    columns = categorical_cols,
    drop_first = True
)

df_encoded.head()

,TransactionAmount,TransactionType,Location,Channel,CustomerAge,CustomerOccupation,TransactionDuration,LoginAttempts,AccountBalance,New_Column,Target
0,14.09,1,36,0,70.0,0,81.0,1.0,5112.21,0,labels
1,376.24,1,15,0,68.0,0,141.0,1.0,13758.91,0,labels
2,126.29,1,23,2,19.0,3,56.0,1.0,1122.35,1,labels
3,184.50,1,33,2,26.0,3,25.0,1.0,8569.06,1,labels
4,92.15,1,28,0,18.0,3,172.0,1.0,781.68,1,labels

In [ ]:
X = df_encoded.drop(columns = ['Target'], axis = 1)
y = df_encoded['Target']

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size = 0.2,
    random_state = 42,
    stratify = y
)

print("Jumlah data total: ",len(X))
print("Jumlah data latih: ",len(X_train))
print("Jumlah data test: ",len(X_test))

Jumlah data total:  2135
Jumlah data latih:  1708
Jumlah data test:  427

In [ ]:
# Buatlah model klasifikasi menggunakan Decision Tree
decision_tree_model = DecisionTreeClassifier(random_state=42)
decision_tree_model.fit(X_train, y_train)

In [ ]:
# Menyimpan Model
joblib.dump(decision_tree_model, 'decision_tree_model.h5')

['decision_tree_model.h5']

In [ ]:
# Melatih model menggunakan algoritma klasifikasi scikit-learn selain Decision Tree. (Contoh: RandomForestClassifier)
new_model = RandomForestClassifier(random_state=42)
new_model.fit(X_train, y_train)

In [ ]:
# Menampilkan hasil evaluasi akurasi, presisi, recall, dan F1-Score pada seluruh algoritma yang sudah dibuat.
y_pred_dt = decision_tree_model.predict(X_test)
y_pred_new = new_model.predict(X_test)

print("Decision Tree Performance")
print(classification_report(y_test, y_pred_dt))

print("="*50)

print("New Model Performance")
print(classification_report(y_test, y_pred_new))

Decision Tree Performance
              precision    recall  f1-score   support

      labels       1.00      1.00      1.00       427

    accuracy                           1.00       427
   macro avg       1.00      1.00      1.00       427
weighted avg       1.00      1.00      1.00       427

==================================================
New Model Performance
              precision    recall  f1-score   support

      labels       1.00      1.00      1.00       427

    accuracy                           1.00       427
   macro avg       1.00      1.00      1.00       427
weighted avg       1.00      1.00      1.00       427

In [ ]:
# Menyimpan Model Selain Decision Tree
joblib.dump(new_model, 'explore_RandomForestClassifier_classification.h5')

['explore_RandomForestClassifier_classification.h5']

In [ ]:
# Hyperparameter tuning 
params = {
    'n_estimators': [100, 200],
    'max_depth': [None, 10, 20],
    'min_samples_split': [2, 5]
    }

new_model_tuned = GridSearchCV(
    estimator = RandomForestClassifier(random_state=42),
    param_grid = params,
    cv = 5,
    scoring = 'accuracy'
)

new_model_tuned.fit(X_train, y_train)

In [ ]:
# Menampilkan hasil evaluasi akurasi, presisi, recall, dan F1-Score pada algoritma yang sudah dituning.

y_pred_tuning = new_model_tuned.predict(X_test)

print("Tuned Model Performance")
print(classification_report(y_test, y_pred_tuning))

Tuned Model Performance
              precision    recall  f1-score   support

      labels       1.00      1.00      1.00       427

    accuracy                           1.00       427
   macro avg       1.00      1.00      1.00       427
weighted avg       1.00      1.00      1.00       427

In [ ]:
# Menyimpan Model hasil tuning
joblib.dump(new_model_tuned, 'tuning_classification.h5')

['tuning_classification.h5']